//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace meseneger1.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class chatmasage
    {
        public Nullable<System.DateTime> date { get; set; }
        public string name { get; set; }
        public Nullable<int> ID_user { get; set; }
        public int iD_mesege { get; set; }
        public string User { get; set; }
    }
}
