//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace meseneger1.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chatrum
    {
        public int ID_rum { get; set; }
        public string NAme { get; set; }
        public int ID_user { get; set; }
    
        public virtual User User { get; set; }
    }
}
